name: cso-network-gas
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - geopandas
  
  # HTML parsing
  - beautifulsoup4
  - html5lib
  - lxml

  # Notebook
  - notebook
  - ipykernel
  - jupytext
